/*
*************************************************************
** Name: SoldToShipToResponse.apxc                        	   **
** Copyright notice: 									   **
** YETI Coolers										       **
*************************************************************
** Purpose:                  							   **
** Sold To Ship To Response structure from Json                    **
*************************************************************
** History:                                                **
************************************************************* 
** VERSION AUTHOR DATE DETAIL RELEASE/CSR                  **
** 1.0 - Satesh Makineni 08/17/2018 INITIAL DEVELOPMENT    **
** 2.0 -                                                   **
*************************************************************
*/

public class SoldToShipToResponse {
    
 	public String BUSINESSPARTNER {get;set;} 
	public String RETURN_Z {get;set;} // in json: RETURN
}