public with sharing class Test {
	public void Test(){
	System.debug('Test');
	System.debug('Test1');
	System.debug('Test1');
	System.debug('Test - Branch');
		System.debug('Test - Branch final');
        System.debug('Test - Branch from org');
        System.debug('Test - Branch from force.com ide');
        System.debug('Test - Branch from force.com ide123');
        System.debug('Test - Branch from force.com ide1234');
        System.debug('Test - Branch from force.com ide12345');
        System.debug('Test - Branch from force.com ide123456');
		
	}
    
}